[webservers]

web-1   ansible_host= fqdn=web-1.ru-central1.internal
web-2   ansible_host= fqdn=web-2.ru-central1.internal

[databases]

main   ansible_host=93.77.190.25 fqdn=fhm80cd8hce7ra4mko34.auto.internal
replica   ansible_host=89.169.159.189 fqdn=fhm1avgesoctb76p8d8r.auto.internal
[storage]

storage   ansible_host=93.77.187.242 fqdn=fhmuge9cb3ri3eagmkc3.auto.internal
